/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface BeerTransform {
    'text': string;
  }
  interface BeerTransformAttributes extends StencilHTMLAttributes {
    'text'?: string;
  }
}

declare global {
  interface StencilElementInterfaces {
    'BeerTransform': Components.BeerTransform;
  }

  interface StencilIntrinsicElements {
    'beer-transform': Components.BeerTransformAttributes;
  }


  interface HTMLBeerTransformElement extends Components.BeerTransform, HTMLStencilElement {}
  var HTMLBeerTransformElement: {
    prototype: HTMLBeerTransformElement;
    new (): HTMLBeerTransformElement;
  };

  interface HTMLElementTagNameMap {
    'beer-transform': HTMLBeerTransformElement
  }

  interface ElementTagNameMap {
    'beer-transform': HTMLBeerTransformElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
